<?php

declare(strict_types=1);

namespace Sova\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260728180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add issue attachment metadata. File bytes live outside the '
            . 'database, addressed by a server-generated storage key.';
    }

    public function up(Schema $schema): void
    {
        // The database keeps only metadata (ADR 0009 / analysis §6.8); the bytes
        // live in the configured storage. `storage_key` is generated by the
        // server and never derived from the uploaded filename, which is what
        // keeps a crafted name from escaping the storage root.
        $this->addSql(<<<'SQL'
            CREATE TABLE issue_attachments (
                id UUID NOT NULL,
                tenant_id UUID NOT NULL,
                project_id UUID NOT NULL,
                issue_id UUID NOT NULL,
                original_name VARCHAR(255) NOT NULL,
                storage_key VARCHAR(255) NOT NULL,
                media_type VARCHAR(160) NOT NULL,
                byte_size BIGINT NOT NULL,
                checksum CHAR(64) NOT NULL,
                scan_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
                scanned_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL,
                uploaded_by_membership_id UUID NOT NULL,
                uploaded_by_user_id UUID DEFAULT NULL,
                deleted_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL,
                deleted_by_user_id UUID DEFAULT NULL,
                created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT pk_issue_attachments PRIMARY KEY (id),
                CONSTRAINT uniq_issue_attachments_storage_key UNIQUE (storage_key),
                CONSTRAINT uniq_issue_attachments_tenant_id UNIQUE (tenant_id, id),
                CONSTRAINT chk_issue_attachments_size CHECK (byte_size > 0),
                CONSTRAINT chk_issue_attachments_checksum CHECK (checksum ~ '^[0-9a-f]{64}$'),
                CONSTRAINT chk_issue_attachments_name CHECK (btrim(original_name) <> ''),
                CONSTRAINT chk_issue_attachments_scan CHECK (
                    scan_status IN ('PENDING', 'CLEAN', 'INFECTED', 'SKIPPED')
                ),
                CONSTRAINT chk_issue_attachments_deleted CHECK (
                    (deleted_at IS NULL AND deleted_by_user_id IS NULL)
                    OR (deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL)
                ),
                CONSTRAINT fk_issue_attachments_issue
                    FOREIGN KEY (tenant_id, project_id, issue_id)
                    REFERENCES issues (tenant_id, project_id, id) ON DELETE CASCADE,
                CONSTRAINT fk_issue_attachments_uploader
                    FOREIGN KEY (tenant_id, uploaded_by_membership_id)
                    REFERENCES tenant_memberships (tenant_id, id) ON DELETE RESTRICT,
                CONSTRAINT fk_issue_attachments_uploader_user
                    FOREIGN KEY (uploaded_by_user_id)
                    REFERENCES users (id) ON DELETE RESTRICT,
                CONSTRAINT fk_issue_attachments_deleted_by
                    FOREIGN KEY (deleted_by_user_id)
                    REFERENCES users (id) ON DELETE RESTRICT
            )
            SQL);

        // Listing an issue's live attachments, and counting them against the
        // per-issue cap.
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_issue_attachments_issue
                ON issue_attachments (tenant_id, issue_id, created_at, id)
                WHERE deleted_at IS NULL
            SQL);

        // The tenant quota is the sum over live rows.
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_issue_attachments_tenant_live
                ON issue_attachments (tenant_id)
                WHERE deleted_at IS NULL
            SQL);

        // Soft-deleted rows are purged after their retention window.
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_issue_attachments_deleted
                ON issue_attachments (deleted_at)
                WHERE deleted_at IS NOT NULL
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS issue_attachments');
    }
}
